INSERT INTO product(product_name, product_count, product_price) VALUES ('jabluko', '10', '0.20')
INSERT INTO product(product_name, product_count, product_price) VALUES ('chleb', '10', '2.80')
INSERT INTO product(product_name, product_count, product_price) VALUES ('piwo', '666', '4.50')
INSERT INTO product(product_name, product_count, product_price) VALUES ('wodka', '666', '20.00')
INSERT INTO product(product_name, product_count, product_price) VALUES ('miod pitny', '66', '60.00')
INSERT INTO product(product_name, product_count, product_price) VALUES ('sake', '4', '80.00')

INSERT INTO user(name, surname, mail, phone, login, password) VALUES ('aaa', 'aaa', 'aaa', '000', 'aaa', 'aaa')
INSERT INTO user(name, surname, mail, phone, login, password) VALUES ('bbb', 'bbb', 'bbb', '111', 'bbb', 'bbb')
INSERT INTO user(name, surname, mail, phone, login, password) VALUES ('ccc', 'ccc', 'ccc', '222', 'ccc', 'ccc')
INSERT INTO user(name, surname, mail, phone, login, password) VALUES ('ddd', 'ddd', 'ddd', '333', 'ddd', 'ddd')
INSERT INTO user(name, surname, mail, phone, login, password) VALUES ('eee', 'eee', 'eee', '444', 'eee', 'eee')
INSERT INTO user(name, surname, mail, phone, login, password) VALUES ('fff', 'fff', 'fff', '555', 'fff', 'fff')
INSERT INTO user(name, surname, mail, phone, login, password) VALUES ('ggg', 'ggg', 'ggg', '666', 'ggg', 'ggg')